PRESETS = {
    "BEAN": {
        "name": "Bean",
        "elongation": 0.95,
        "sharpness": 0,
        "hardness": 0.40,
        "bulge": -1.0,
        "bend": -1.0,
        "mode": "ADD",
        "clamp": True,
        "rotation": 0,
    },
    "BOWL": {
        "name": "Bowl",
        "elongation": 0.91,
        "sharpness": 0.77,
        "hardness": 0.27,
        "bulge": 0,
        "bend": 0,
        "mode": "ADD",
        "clamp": True,
        "rotation": 0,
    },
    "LEAF": {
        "name": "Leaf",
        "elongation": 0.28,
        "sharpness": 1.0,
        "hardness": 0.28,
        "bulge": 0,
        "bend": 0,
        "mode": "ADD",
        "clamp": True,
        "rotation": 0,
    },
    "WORM": {
        "name": "Worm",
        "elongation": 1.0,
        "sharpness": 0,
        "hardness": 0.76,
        "bulge": 1.0,
        "bend": 1.0,
        "mode": "ADD",
        "clamp": True,
        "rotation": 30,
    },
    "CAPSULE": {
        "name": "Capsule",
        "elongation": 0.88,
        "sharpness": 0.06,
        "hardness": 0.46,
        "bulge": -1.0,
        "bend": 1.0,
        "mode": "LIGHTEN",
        "clamp": True,
        "rotation": 0,
    },
    "CRESCENT": {
        "name": "Crescent",
        "elongation": 0.92,
        "sharpness": 1.00,
        "hardness": 1.00,
        "bulge": -1.0,
        "bend": -1.0,
        "mode": "LIGHTEN",
        "clamp": True,
        "rotation": 0,
    },
    "TRIANGLE": {
        "name": "Triangle",
        "elongation": 0.60,
        "sharpness": 0.98,
        "hardness": 0.25,
        "bulge": -0.92,
        "bend": -0.8,
        "mode": "LIGHTEN",
        "clamp": True,
        "rotation": 9,
    },
    "PARABOLA": {
        "name": "Parabola",
        "elongation": 0.78,
        "sharpness": 0.58,
        "hardness": 0.25,
        "bulge": -0.92,
        "bend": -0.8,
        "mode": "LIGHTEN",
        "clamp": True,
        "rotation": 9,
    },
    "BUTTE": {
        "name": "Butte",
        "elongation": 0.78,
        "sharpness": 0.58,
        "hardness": 0.25,
        "bulge": -0.92,
        "bend": -0.8,
        "mode": "ADD",
        "clamp": True,
        "rotation": 9,
    },
}